// SettingsDataSource
// This file was auto-Generated by Flutter Bunny Cli🐰
import '../models/settings_model.dart';

abstract class SettingsDataSource {
  Future<List<SettingsModel>> getAll();
  Future<SettingsModel> getById(String id);
  Future<void> create(SettingsModel model);
  Future<void> update(SettingsModel model);
  Future<void> delete(String id);
}

class SettingsRemoteDataSource implements SettingsDataSource {
  // TODO: Implement remote data source (API calls, etc.)
  
  @override
  Future<List<SettingsModel>> getAll() async {
    // TODO: Implement API call
    return [];
  }
  
  @override
  Future<SettingsModel> getById(String id) async {
    // TODO: Implement API call
    throw UnimplementedError();
  }
  
  @override
  Future<void> create(SettingsModel model) async {
    // TODO: Implement API call
  }
  
  @override
  Future<void> update(SettingsModel model) async {
    // TODO: Implement API call
  }
  
  @override
  Future<void> delete(String id) async {
    // TODO: Implement API call
  }
}

class SettingsLocalDataSource implements SettingsDataSource {
  // TODO: Implement local data source (shared prefs, database, etc.)
  
  @override
  Future<List<SettingsModel>> getAll() async {
    // TODO: Implement local storage retrieval
    return [];
  }
  
  @override
  Future<SettingsModel> getById(String id) async {
    // TODO: Implement local storage retrieval
    throw UnimplementedError();
  }
  
  @override
  Future<void> create(SettingsModel model) async {
    // TODO: Implement local storage saving
  }
  
  @override
  Future<void> update(SettingsModel model) async {
    // TODO: Implement local storage updating
  }
  
  @override
  Future<void> delete(String id) async {
    // TODO: Implement local storage deletion
  }
}
