// This file was auto-Generated by Flutter Bunny Cli🐰

import 'package:eco_locator/features/locator/domain/entities/recycling_point.dart';

class RecyclingPointModel extends RecyclingPoint {
  RecyclingPointModel({
    required String nome,
    required List<String> materials,
    required double latitude,
    required double longitude,
  }) : super(
          nome: nome,
          materials: materials,
          latitude: latitude,
          longitude: longitude,
        );

  factory RecyclingPointModel.fromJson(Map<String, dynamic> json) {
    return RecyclingPointModel(
      nome: json['name'],
      materials:
          (json['materials'] as List<dynamic>).map((e) => e as String).toList(),
      latitude: json['latitude'],
      longitude: json['longitude']
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'nome': nome,
      'materials': materials,
      'latitude': latitude,
      'longitude': longitude
    };
  }

  factory RecyclingPointModel.fromEntity(RecyclingPoint entity) {
    return RecyclingPointModel(
      nome: entity.nome,
      materials: entity.materials,
      latitude: entity.latitude,
      longitude: entity.longitude,
    );
  }

  // to string
  @override
  String toString() {
    return 'RecyclingPointModel(nome: $nome, type: $materials, latitude: $latitude, longitude: $longitude)';
  }
}
