// SettingsWidget
// This file was auto-Generated by Flutter Bunny Cli🐰
import 'package:flutter/material.dart';

class SettingsWidget extends StatelessWidget {
  const SettingsWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Settings Feature'),
    );
  }
}
