// SettingsRepositoryImpl
// This file was auto-Generated by Flutter Bunny Cli🐰
import '../../domain/entities/settings_entity.dart';
import '../../domain/repositories/settings_repository.dart';
import '../datasources/settings_data_source.dart';
import '../models/settings_model.dart';

class SettingsRepositoryImpl implements SettingsRepository {
  final SettingsDataSource dataSource;
  
  SettingsRepositoryImpl({
    required this.dataSource,
  });
  
  @override
  Future<List<SettingsEntity>> getAll() async {
    final result = await dataSource.getAll();
    return result.map((model) => model).toList();
  }
  
  @override
  Future<SettingsEntity> getById(String id) async {
    return await dataSource.getById(id);
  }
  
  @override
  Future<void> create(SettingsEntity entity) async {
    await dataSource.create(SettingsModel.fromEntity(entity));
  }
  
  @override
  Future<void> update(SettingsEntity entity) async {
    await dataSource.update(SettingsModel.fromEntity(entity));
  }
  
  @override
  Future<void> delete(String id) async {
    await dataSource.delete(id);
  }
}
