// SettingsRepository interface
// This file was auto-Generated by Flutter Bunny Cli🐰
import '../entities/settings_entity.dart';

abstract class SettingsRepository {
  Future<List<SettingsEntity>> getAll();
  Future<SettingsEntity> getById(String id);
  Future<void> create(SettingsEntity entity);
  Future<void> update(SettingsEntity entity);
  Future<void> delete(String id);
}
