// SettingsPage
// This file was auto-Generated by Flutter Bunny Cli🐰
import 'package:flutter/material.dart';
import '../widgets/settings_widget.dart';

class SettingsPage extends StatelessWidget {
  const SettingsPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Settings'),
      ),
      body: SettingsWidget(),
    );
  }
}
