// SettingsUseCase
// This file was auto-Generated by Flutter Bunny Cli🐰
import '../entities/settings_entity.dart';
import '../repositories/settings_repository.dart';

class GetSettingsUseCase {
  final SettingsRepository repository;
  
  GetSettingsUseCase(this.repository);
  
  Future<List<SettingsEntity>> execute() {
    return repository.getAll();
  }
}

class GetSettingsByIdUseCase {
  final SettingsRepository repository;
  
  GetSettingsByIdUseCase(this.repository);
  
  Future<SettingsEntity> execute(String id) {
    return repository.getById(id);
  }
}
